version: '3.1'
services:
    env-api:
        container_name: env-api
        restart: always
        build:
            context: api
            dockerfile: Dockerfile
        ports:
            - '3000:3000'
        depends_on:
            - env-mongo
            - redis-env

    env-mongo:
        container_name: env-mongo
        image: mongo:6.0
        restart: always
        environment:
            MONGO_DATA_DIR: /data/db
            MONGO_LOG_DIR: /dev/null
        ports:
            - '27017:27017'
        command: mongod --logpath=/dev/null # --quiet

    redis-env:
        container_name: redis-env
        image: redis:6.2.7
        restart: always
        ports:
            - "6379:6379"
       
        
        
